inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  Exclude:
    - gemfiles/vendor/**/*

Style/MethodCallWithArgsParentheses:
  Exclude:
    - Gemfile
    - gemfiles/*
